exo2: exo2.o 
		g++ exo2.o -o exo2.exe
	
exo2.o: exo2.cpp
		g++ -c exo2.cpp
	
MonPremierFichierTexte: MonPremierFichierTexte.o 
		g++ MonPremierFichierTexte.o -o MonPremierFichierTexte.exe
		
MonPremierFichierTexte.o: MonPremierFichierTexte.cpp
		g++ -c MonPremierFichierTexte.cpp	

clean: 
	rm -f *.o *.exe